---
Name: rest_api
After:
  - 'framework/*'
  - 'cms/*'
---
AuthFactory:
  AuthType: TokenAuth
TokenAuth:
  DevToken: foobarbaz
JwtAuth:
  Key: LoremIpsum
  HashAlgorithm: sha256
  Issuer: "rest.ntb.dev"
  ExpireTime: 1209600
BaseRestController:
  CORSOrigin: '*'
  CORSMethods: 'GET, PUT, POST, DELETE, OPTIONS'
  CORSMaxAge: '1000'
  CORSAllowHeaders: 'Content-Type, Authorization, X-Requested-With'
  Owner: Member